### ISSUE TITLE
Wind charts

### ISSUE THREAD

**Issue by jamiem876** [golf-clash-notebook/golf-clash-notebook.github.io#195]
Love all the content on this site, but just have a question about the accuracy of the updated wind charts.... I recently hit a perfect max power shot (not overpowered) with my level 2 spitfire in 6.0 mph wind. It landed within the clear ring, which based on the current guide should be the 10-13 mph range. 

It has 50 accuracy, which generally should be about 2 mph per ring. Are the current wind charts accurate? This is the first shot I have taken with the updated charts that landed well outside of the projected ring...

**Comment by cranst0n** [comment]
@jamiem876 Do you have a video of the shot? That will help determining what the issue was. The charts in general are just a starting point for adjustments as other factors like elevation will also determine the number of rings you need to move.

Also, the current chart values for rough irons and sand wedges may not be exact. They are based on input from other players, using trial and error. Those values in particular may be adjusted in the future if needed. As of today, a 120 yard wedge with 100 accuracy (e.g. Spitfire 6+) will have a ring value of 1.6MPH per ring.

**Comment by jamiem876** [comment]
Here is a clip of the shot. It lands within the clear ring, which is 10-13 mph of wind according to the guide. The wind for the shot was only 6mph. Let me know if I'm misreading the shot or missing something obvious that would have affected the shot so much. 

https://photos.app.goo.gl/kufcxWdqfAqJWbX1A

**Comment by cranst0n** [comment]
Maybe splitting hairs here but to my eye, I think it lands around the edge of the blue ring, which still doesn't totally account for the miss I guess. The shot doesn't really look downhill to me but I'm not really sure. I would post this to [Golf Clash Learn or Burn](https://www.facebook.com/groups/221951588555223/) and you'll probably get a more informed answer than I can give you. And it's always possible the chart is off. Sand Wedge and Rough Iron values are the least reliable on the chart.
